import { MigrationInterface, QueryRunner } from "typeorm";

export class Recipe1788789524951 implements MigrationInterface {
    name = "Recipe1788789524951";

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`recipe_ingredient\` DROP FOREIGN KEY \`fk_ri_ingredient\``);
        await queryRunner.query(`ALTER TABLE \`recipe_ingredient\` DROP FOREIGN KEY \`fk_ri_recipe\``);
        await queryRunner.query(`ALTER TABLE \`recipe_seasoning\` DROP FOREIGN KEY \`fk_rs_recipe\``);
        await queryRunner.query(`ALTER TABLE \`recipe_seasoning\` DROP FOREIGN KEY \`fk_rs_seasoning\``);
        await queryRunner.query(`ALTER TABLE \`recipe_supplementary\` DROP FOREIGN KEY \`fk_rsup_recipe\``);
        await queryRunner.query(`ALTER TABLE \`recipe_supplementary\` DROP FOREIGN KEY \`fk_rsup_supplementary\``);
        await queryRunner.query(`DROP INDEX \`uk_recipe_ingredient\` ON \`recipe_ingredient\``);
        await queryRunner.query(`DROP INDEX \`idx_ingredient_id\` ON \`recipe_ingredient\``);
        await queryRunner.query(`DROP INDEX \`uk_recipe_seasoning\` ON \`recipe_seasoning\``);
        await queryRunner.query(`DROP INDEX \`idx_seasoning_id\` ON \`recipe_seasoning\``);
        await queryRunner.query(`DROP INDEX \`uk_name\` ON \`supplementary\``);
        await queryRunner.query(`DROP INDEX \`uk_recipe_supplementary\` ON \`recipe_supplementary\``);
        await queryRunner.query(`DROP INDEX \`idx_supplementary_id\` ON \`recipe_supplementary\``);
        await queryRunner.query(`ALTER TABLE \`recipe_ingredient\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`recipe_seasoning\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`supplementary\` COMMENT ''`);
        await queryRunner.query(`ALTER TABLE \`recipe_supplementary\` COMMENT ''`);
        await queryRunner.query(`CREATE TABLE \`meeting_room\` (\`id\` varchar(36) NOT NULL COMMENT '会议室id', \`name\` varchar(255) NOT NULL COMMENT '会议室名称', \`capacity\` int NOT NULL COMMENT '会议室容量', \`location\` varchar(255) NOT NULL COMMENT '会议室位置', \`equipment\` varchar(255) NOT NULL COMMENT '会议室设备', \`desc\` varchar(255) NOT NULL COMMENT '会议室描述', \`createTime\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`updateTime\` datetime(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`meeting_room_bookings\` (\`id\` int NOT NULL AUTO_INCREMENT, \`startTime\` datetime NOT NULL, \`endTime\` datetime NOT NULL, \`status\` varchar(255) NOT NULL, \`createTime\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`meetingRoomId\` varchar(36) NULL COMMENT '会议室id', \`userId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`ingredient\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '食材id'`);
        await queryRunner.query(`ALTER TABLE \`ingredient\` CHANGE \`name\` \`name\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`ingredient\` CHANGE \`remark\` \`remark\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`recipe_ingredient\` CHANGE \`recipe_id\` \`recipe_id\` bigint UNSIGNED NULL COMMENT '菜id'`);
        await queryRunner.query(`ALTER TABLE \`recipe_ingredient\` CHANGE \`ingredient_id\` \`ingredient_id\` bigint UNSIGNED NULL COMMENT '食材id'`);
        await queryRunner.query(`ALTER TABLE \`seasoning\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '调料id'`);
        await queryRunner.query(`ALTER TABLE \`seasoning\` CHANGE \`name\` \`name\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`seasoning\` CHANGE \`remark\` \`remark\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`recipe_seasoning\` CHANGE \`recipe_id\` \`recipe_id\` bigint UNSIGNED NULL COMMENT '菜id'`);
        await queryRunner.query(`ALTER TABLE \`recipe_seasoning\` CHANGE \`seasoning_id\` \`seasoning_id\` bigint UNSIGNED NULL COMMENT '调料id'`);
        await queryRunner.query(`ALTER TABLE \`supplementary\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '辅料id'`);
        await queryRunner.query(`ALTER TABLE \`supplementary\` CHANGE \`name\` \`name\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`supplementary\` CHANGE \`remark\` \`remark\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`recipe_supplementary\` CHANGE \`recipe_id\` \`recipe_id\` bigint UNSIGNED NULL COMMENT '菜id'`);
        await queryRunner.query(`ALTER TABLE \`recipe_supplementary\` CHANGE \`supplementary_id\` \`supplementary_id\` bigint UNSIGNED NULL COMMENT '辅料id'`);
        await queryRunner.query(`ALTER TABLE \`recipe\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '菜id'`);
        await queryRunner.query(`ALTER TABLE \`recipe\` CHANGE \`name\` \`name\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`recipe\` CHANGE \`calories_per_100g\` \`calories_per_100g\` decimal(6,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`recipe\` CHANGE \`difficulty\` \`difficulty\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`recipe\` CHANGE \`cooking_time\` \`cooking_time\` smallint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`recipe\` CHANGE \`cuisine_type\` \`cuisine_type\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`recipe\` CHANGE \`kitchenware\` \`kitchenware\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`recipe\` CHANGE \`flavor\` \`flavor\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`recipe\` CHANGE \`effectImg\` \`effectImg\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`recipe_step\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`recipe_step\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`recipe_step\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`recipe_step\` ADD \`id\` bigint UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '步骤id'`);
        await queryRunner.query(`ALTER TABLE \`recipe_step\` DROP COLUMN \`recipe_id\``);
        await queryRunner.query(`ALTER TABLE \`recipe_step\` ADD \`recipe_id\` bigint UNSIGNED NULL COMMENT '菜id'`);
        await queryRunner.query(`ALTER TABLE \`recipe_ingredient\` ADD CONSTRAINT \`FK_256c22ec24d2d590b39e11a3ee4\` FOREIGN KEY (\`recipe_id\`) REFERENCES \`recipe\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`recipe_ingredient\` ADD CONSTRAINT \`FK_e1948973c93c7cabca7522b6ff3\` FOREIGN KEY (\`ingredient_id\`) REFERENCES \`ingredient\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`recipe_seasoning\` ADD CONSTRAINT \`FK_e9c50370ec596bd546dc06f2e79\` FOREIGN KEY (\`recipe_id\`) REFERENCES \`recipe\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`recipe_seasoning\` ADD CONSTRAINT \`FK_6d24994e15fef8a9ec1eabc1439\` FOREIGN KEY (\`seasoning_id\`) REFERENCES \`seasoning\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`recipe_supplementary\` ADD CONSTRAINT \`FK_1a7fccd98796ecb6db3f8b0bab0\` FOREIGN KEY (\`recipe_id\`) REFERENCES \`recipe\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`recipe_supplementary\` ADD CONSTRAINT \`FK_814632a1ec393eeac952569f9d0\` FOREIGN KEY (\`supplementary_id\`) REFERENCES \`supplementary\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`recipe_step\` ADD CONSTRAINT \`FK_c0f69d7b4eece2f0207e4a4f6d2\` FOREIGN KEY (\`recipe_id\`) REFERENCES \`recipe\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`meeting_room_bookings\` ADD CONSTRAINT \`FK_63a38e5d765d0a88d358cd10f8e\` FOREIGN KEY (\`meetingRoomId\`) REFERENCES \`meeting_room\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`meeting_room_bookings\` ADD CONSTRAINT \`FK_b776c2be0468a0d42257e77bacd\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_permission_relation\` ADD CONSTRAINT \`FK_e1ca88973e6058882146e254018\` FOREIGN KEY (\`roleId\`) REFERENCES \`role\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`role_permission_relation\` ADD CONSTRAINT \`FK_7822b319e3e15d982d49aa50cf2\` FOREIGN KEY (\`permissionId\`) REFERENCES \`permission\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_role_relation\` ADD CONSTRAINT \`FK_387a09a362c32ee04b33fc4eaab\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_role_relation\` ADD CONSTRAINT \`FK_bed18db98a78c46f0bcfedfe652\` FOREIGN KEY (\`roleId\`) REFERENCES \`role\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_role_relation\` DROP FOREIGN KEY \`FK_bed18db98a78c46f0bcfedfe652\``);
        await queryRunner.query(`ALTER TABLE \`user_role_relation\` DROP FOREIGN KEY \`FK_387a09a362c32ee04b33fc4eaab\``);
        await queryRunner.query(`ALTER TABLE \`role_permission_relation\` DROP FOREIGN KEY \`FK_7822b319e3e15d982d49aa50cf2\``);
        await queryRunner.query(`ALTER TABLE \`role_permission_relation\` DROP FOREIGN KEY \`FK_e1ca88973e6058882146e254018\``);
        await queryRunner.query(`ALTER TABLE \`meeting_room_bookings\` DROP FOREIGN KEY \`FK_b776c2be0468a0d42257e77bacd\``);
        await queryRunner.query(`ALTER TABLE \`meeting_room_bookings\` DROP FOREIGN KEY \`FK_63a38e5d765d0a88d358cd10f8e\``);
        await queryRunner.query(`ALTER TABLE \`recipe_step\` DROP FOREIGN KEY \`FK_c0f69d7b4eece2f0207e4a4f6d2\``);
        await queryRunner.query(`ALTER TABLE \`recipe_supplementary\` DROP FOREIGN KEY \`FK_814632a1ec393eeac952569f9d0\``);
        await queryRunner.query(`ALTER TABLE \`recipe_supplementary\` DROP FOREIGN KEY \`FK_1a7fccd98796ecb6db3f8b0bab0\``);
        await queryRunner.query(`ALTER TABLE \`recipe_seasoning\` DROP FOREIGN KEY \`FK_6d24994e15fef8a9ec1eabc1439\``);
        await queryRunner.query(`ALTER TABLE \`recipe_seasoning\` DROP FOREIGN KEY \`FK_e9c50370ec596bd546dc06f2e79\``);
        await queryRunner.query(`ALTER TABLE \`recipe_ingredient\` DROP FOREIGN KEY \`FK_e1948973c93c7cabca7522b6ff3\``);
        await queryRunner.query(`ALTER TABLE \`recipe_ingredient\` DROP FOREIGN KEY \`FK_256c22ec24d2d590b39e11a3ee4\``);
        await queryRunner.query(`ALTER TABLE \`recipe_step\` DROP COLUMN \`recipe_id\``);
        await queryRunner.query(`ALTER TABLE \`recipe_step\` ADD \`recipe_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`recipe_step\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`recipe_step\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`recipe_step\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`recipe_step\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`recipe\` CHANGE \`effectImg\` \`effectImg\` varchar(255) CHARACTER SET "utf8mb4" COLLATE "utf8mb4_general_ci" NULL COMMENT '效果图片URL'`);
        await queryRunner.query(`ALTER TABLE \`recipe\` CHANGE \`flavor\` \`flavor\` varchar(50) CHARACTER SET "utf8mb4" COLLATE "utf8mb4_general_ci" NULL COMMENT '口味'`);
        await queryRunner.query(`ALTER TABLE \`recipe\` CHANGE \`kitchenware\` \`kitchenware\` varchar(100) CHARACTER SET "utf8mb4" COLLATE "utf8mb4_general_ci" NULL COMMENT '厨具'`);
        await queryRunner.query(`ALTER TABLE \`recipe\` CHANGE \`cuisine_type\` \`cuisine_type\` varchar(50) CHARACTER SET "utf8mb4" COLLATE "utf8mb4_general_ci" NULL COMMENT '菜系/分类'`);
        await queryRunner.query(`ALTER TABLE \`recipe\` CHANGE \`cooking_time\` \`cooking_time\` smallint UNSIGNED NOT NULL COMMENT '耗时(分钟)'`);
        await queryRunner.query(`ALTER TABLE \`recipe\` CHANGE \`difficulty\` \`difficulty\` tinyint NULL COMMENT '难度 1简单 2中等 3困难' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`recipe\` CHANGE \`calories_per_100g\` \`calories_per_100g\` decimal(6,2) NULL COMMENT '100g多少大卡' DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`recipe\` CHANGE \`name\` \`name\` varchar(100) CHARACTER SET "utf8mb4" COLLATE "utf8mb4_general_ci" NOT NULL COMMENT '菜名'`);
        await queryRunner.query(`ALTER TABLE \`recipe\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`recipe_supplementary\` CHANGE \`supplementary_id\` \`supplementary_id\` bigint UNSIGNED NOT NULL COMMENT '辅料ID'`);
        await queryRunner.query(`ALTER TABLE \`recipe_supplementary\` CHANGE \`recipe_id\` \`recipe_id\` bigint UNSIGNED NOT NULL COMMENT '食谱ID'`);
        await queryRunner.query(`ALTER TABLE \`supplementary\` CHANGE \`remark\` \`remark\` varchar(255) CHARACTER SET "utf8mb4" COLLATE "utf8mb4_unicode_ci" NULL COMMENT '备注'`);
        await queryRunner.query(`ALTER TABLE \`supplementary\` CHANGE \`name\` \`name\` varchar(50) CHARACTER SET "utf8mb4" COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT '辅料名'`);
        await queryRunner.query(`ALTER TABLE \`supplementary\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID'`);
        await queryRunner.query(`ALTER TABLE \`recipe_seasoning\` CHANGE \`seasoning_id\` \`seasoning_id\` bigint UNSIGNED NOT NULL COMMENT '调料ID'`);
        await queryRunner.query(`ALTER TABLE \`recipe_seasoning\` CHANGE \`recipe_id\` \`recipe_id\` bigint UNSIGNED NOT NULL COMMENT '食谱ID'`);
        await queryRunner.query(`ALTER TABLE \`seasoning\` CHANGE \`remark\` \`remark\` varchar(255) CHARACTER SET "utf8mb4" COLLATE "utf8mb4_unicode_ci" NULL COMMENT '备注'`);
        await queryRunner.query(`ALTER TABLE \`seasoning\` CHANGE \`name\` \`name\` varchar(50) CHARACTER SET "utf8mb4" COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT '调料名'`);
        await queryRunner.query(`ALTER TABLE \`seasoning\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID'`);
        await queryRunner.query(`ALTER TABLE \`recipe_ingredient\` CHANGE \`ingredient_id\` \`ingredient_id\` bigint UNSIGNED NOT NULL COMMENT '食材ID'`);
        await queryRunner.query(`ALTER TABLE \`recipe_ingredient\` CHANGE \`recipe_id\` \`recipe_id\` bigint UNSIGNED NOT NULL COMMENT '食谱ID'`);
        await queryRunner.query(`ALTER TABLE \`ingredient\` CHANGE \`remark\` \`remark\` varchar(255) CHARACTER SET "utf8mb4" COLLATE "utf8mb4_general_ci" NULL COMMENT '备注'`);
        await queryRunner.query(`ALTER TABLE \`ingredient\` CHANGE \`name\` \`name\` varchar(50) CHARACTER SET "utf8mb4" COLLATE "utf8mb4_general_ci" NOT NULL COMMENT '食材名'`);
        await queryRunner.query(`ALTER TABLE \`ingredient\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`DROP TABLE \`meeting_room_bookings\``);
        await queryRunner.query(`DROP TABLE \`meeting_room\``);
        await queryRunner.query(`ALTER TABLE \`recipe_supplementary\` COMMENT '食谱与辅料关联表'`);
        await queryRunner.query(`ALTER TABLE \`supplementary\` COMMENT '辅料字典表'`);
        await queryRunner.query(`ALTER TABLE \`recipe_seasoning\` COMMENT '食谱与调料关联表'`);
        await queryRunner.query(`ALTER TABLE \`recipe_ingredient\` COMMENT '食谱与食材关联表'`);
        await queryRunner.query(`CREATE INDEX \`idx_supplementary_id\` ON \`recipe_supplementary\` (\`supplementary_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`uk_recipe_supplementary\` ON \`recipe_supplementary\` (\`recipe_id\`, \`supplementary_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`uk_name\` ON \`supplementary\` (\`name\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_seasoning_id\` ON \`recipe_seasoning\` (\`seasoning_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`uk_recipe_seasoning\` ON \`recipe_seasoning\` (\`recipe_id\`, \`seasoning_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_ingredient_id\` ON \`recipe_ingredient\` (\`ingredient_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`uk_recipe_ingredient\` ON \`recipe_ingredient\` (\`recipe_id\`, \`ingredient_id\`)`);
        await queryRunner.query(`ALTER TABLE \`recipe_supplementary\` ADD CONSTRAINT \`fk_rsup_supplementary\` FOREIGN KEY (\`supplementary_id\`) REFERENCES \`supplementary\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`recipe_supplementary\` ADD CONSTRAINT \`fk_rsup_recipe\` FOREIGN KEY (\`recipe_id\`) REFERENCES \`recipe\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`recipe_seasoning\` ADD CONSTRAINT \`fk_rs_seasoning\` FOREIGN KEY (\`seasoning_id\`) REFERENCES \`seasoning\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`recipe_seasoning\` ADD CONSTRAINT \`fk_rs_recipe\` FOREIGN KEY (\`recipe_id\`) REFERENCES \`recipe\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`recipe_ingredient\` ADD CONSTRAINT \`fk_ri_recipe\` FOREIGN KEY (\`recipe_id\`) REFERENCES \`recipe\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`recipe_ingredient\` ADD CONSTRAINT \`fk_ri_ingredient\` FOREIGN KEY (\`ingredient_id\`) REFERENCES \`ingredient\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
    }
}
